const String supabaseUrl = 'https://idvowhpwpwmmjlryueqd.supabase.co';
const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlkdm93aHB3cHdtbWpscnl1ZXFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA2OTA0MzUsImV4cCI6MjA5NjI2NjQzNX0.0NsTpl9b-vnSpBahuZ61GK2SJRYXAf0OVeIUJR-tB6g';
